### ISSUE TITLE
Schema changes in binding QIF3.0DocumentBundle2020Jun8.zip

### ISSUE THREAD

**Issue by ratboydad** [QualityInformationFramework/qif-community#10]
In the qif/community/bindings file “QIF3.0DocumentBundle2020Jun8.zip”, unzipped, there is file in the “**schema**” directory named “**schemaChanges**”. Do these schema changes **supersede** those of the original 3.0 schema which I have downloaded (QIF3.0-2018-ANSI.zip), or were those changes simply to get that particular binding to work?

**Comment by TomRKramer** [comment]
Hello ? -

The changes described in the schemaChanges do not supersede the original QIF3.0 schema. The changes were made to enable using an automatic code generator to generate (1) the C++ classes for QIF3.0 and (2) the QIF3.0 instance file parser that are included in the bundle. With one exception, every QIF3.0 instance file that is valid against the original QIF3.0 schema can be parsed by the parser and represented in terms of the classes. The exception is UserDataXML cannot be included in AttributeUserType. Two items in an instance file will be represented as strings in the classes and will not be checked by the parser for being valid. Those are:
    digital signature
    UserDataXML

The parser checks that everything else in an instance file is syntactically valid. The parser does not check validity against constraints (key, keyref, unique).

The generator used to generate the parser and classes is now available at https://sourceforge.net/projects/xml-parsers-and-utilities.

I hope that is helpful and will be happy to answer further questions.

Tom Kramer

From: ratboydad ***@***.***>
Sent: Monday, March 22, 2021 10:51 AM
To: QualityInformationFramework/qif-community ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [QualityInformationFramework/qif-community] Schema changes in binding QIF3.0DocumentBundle2020Jun8.zip (#10)


In the qif/community/bindings file "QIF3.0DocumentBundle2020Jun8.zip", unzipped, there is file in the "schema" directory named "schemaChanges". Do these schema changes supersede those of the original 3.0 schema which I have downloaded (QIF3.0-2018-ANSI.zip), or were those changes simply to get that particular binding to work?

-
