### ISSUE TITLE
Change license agreement to a known open-source license

### ISSUE THREAD

**Issue by MatthewPowley** [QualityInformationFramework/qif-community#2]
The license agreement within this software should be changed to a known open-source license, such as Apache 2.0, Boost etc....

This way anybody that uses this code in a commercial company does not have to pay expensive lawyers to read another bespoke license and provide guidance.

Additionally; by using a known open-source software license, the open-source version of Code Synthesis XML data binding tool can be used, as "this software" would be governed by their FLOSS exception. This would allow commercial companies who would like to use QIF in C++ to use these samples without first having to sign license agreements and incur costs.

**Comment by daniel-campbell** [comment]
Hi Matt, thanks for this excellent suggestion! We will discuss changing to a standard OSS agreement. I think that your suggestions makes very good sense.

**Comment by daniel-campbell** [comment]
We have updated the licenses to use the BOOST Standard License: 3fdb0a37fb870fb2fcd51fbc69476b1332d1b62a
