### ISSUE TITLE
Extend the number of options provided by SubstituteFeatureAlgorithm.

### ISSUE THREAD

**Issue by GitHubDaveSmith** [QualityInformationFramework/qif-community#23]
This is for those situations where a feature is referenced by two or more characteristic measurements and the fitting algorithm used is different in each case.
Consider a circularity characteristic that has been evaluated on a circle feature. The data fitting algorithm is LEASTSQUARES in this case, and this is reported for both the characteristic and the feature using the element SubstituteFeatureAlgorithm. The measured feature also reports its location, normal and diameter. 
Now suppose we apply another characteristic to the same feature but this time we use the MINMAX fitting algorithm. We again use SubstituteFeatureAlgorithm to report the fitting algorithm but we also need to report a new location, normal and diameter since these might change given that originally the feature will have been evaluated using the ‘LEASTSQUARES’ algorithm. If the centre and/or direction do change then the perceived deviation might also change depending on the characteristic that is being reported.
We are using a custom attribute to do this.
While the schema defines a SubstituteFeatueAlgorithmEnum which allows a number of options (including LEASTSQUARES) it does not have any fields for position, direction etc. determined by the specified fitting algorithm.
 
See attached document for sample QIF.

[CustomAttributeForFeatureFittingAlgorithm.docx](https://github.com/QualityInformationFramework/qif-community/files/8708590/CustomAttributeForFeatureFittingAlgorithm.docx)

**Comment by daniel-campbell** [comment]
This is good -- there is a related issue here: https://github.com/QualityInformationFramework/qif-dev/issues/10

**Comment by GitHubDaveSmith** [comment]
Hi Daniel, I'm afraid the link doesn't work for me :(

**Comment by TomRKramer** [comment]
The requested capability is already available in QIF. A sample instance file containing feature measurements derived from the same data using two different algorithms was sent to Dave.
