### ISSUE TITLE
Question about Python source gode example for QIF applications 

### ISSUE THREAD

**Issue by DGW1978** [QualityInformationFramework/qif-community#7]
Hi,

I'm trying to run the Python source code example.
According to the readme file, it says I have to copy a QIF schema file into QIF3.0_Open_Source_Apps\Python\PyXB\QIFApplications folder, but I cannot find any schema file in the example document.
Does it mean I can simply find a QIF schema file and add it into that folder?
Is it supposed to have a schema file inside the example document which is currently missing?

Dave

**Comment by cstjohn-auto** [comment]
Hi Dave,
You need to download QIF3.0 from the DMSC QIF site.  It contains schemas and the standard in pdf format.  You then drag and drop the schema files out of the XSD folder into the QIFApplications folder. 
Best,
Cole

**Comment by DGW1978** [comment]
Hi Cole,

Thank you for the elaborations!

Best regards,
Dave


山衛科技股份有限公司
Samwells Testing Inc.
新北市汐止區康寧街169巷25號11樓之1
11F-1, No. 25, Lane 169, Kangning St., Xizhi Dist., New Taipei City 22180, Taiwan.
Tel: +886-2-2692-1400
Mobile: +886 963-718-303
e-mail: dave@samwells.com
 
From: Cole St John
Date: 2020-07-08 16:59
To: QualityInformationFramework/qif-community
CC: DGW1978; Author
Subject: Re: [QualityInformationFramework/qif-community] Question about Python source gode example for QIF applications (#7)
Hi Dave,
You need to download QIF3.0 from the DMSC QIF site. It contains schemas and the standard in pdf format. You then drag and drop the schema files out of the XSD folder into the QIFApplications folder.
Best,
Cole
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
Avast 防毒軟體已檢查此封電子郵件的病毒。
https://www.avast.com/antivirus
