### ISSUE TITLE
Distance between two features within a feature group

### ISSUE THREAD

**Issue by GitHubDaveSmith** [QualityInformationFramework/qif-community#9]
Hi,

I was wondering if anybody could supply a sample of QIF that represents a Distance between characteristic that is applied between two features that belong to a group. For example, if my group consists of two cylinders and I want to know the distance between those cylinders I know that my 'DistanceBetweenCharacteristicNominal' will contain a 'FeatureNominalPairs' element that will reference the relevant features, but where is the reference made to the group feature to which these features belong?

A sample would be of great help.

Many thanks

**Comment by daniel-campbell** [comment]
Can you explain what you mean by "group"? 

In the `DistanceBetweenCharacteristicNominal` you should find: 

```
<FeatureNominalPairs n="1">
   <FeaturePair>
     <FirstFeature>1070</FirstFeature> 
     <SecondFeature>1068</SecondFeature> 
   </FeaturePair>
</FeatureNominalPairs>
```

And this would allow you to specify which features constitute the pairs. You can have more than 1 pair. 

Does this answer your question, or did you have something else in mind?

**Comment by GitHubDaveSmith** [comment]
Hi Daniel,

Thank you for your reply.

Unfortunately your answer doesn't really address my problem.

I have done what you have suggested in your email for the DistanceBetween characteristic regarding FeatureNominalPairs. Now imagine that the two features that are referenced as 'FirstFeature' and 'SecondFeature' also belong to a 'GroupFeature'... perhaps they are two cylinders that form the ends of a custom feature that we call 'SpecialSlot' and we want to define a group so that we can report the characteristic against 'SpecialSlot'.

My question is: having defined the distance between characteristic and referenced the two cylinders as 'FirstFeature' and 'SecondFeature' in 'FeatureNominalPairs', how can I then state that the characteristic is measured with respect to 'SpecialSlot'.

Many thanks

Dave

**Comment by TomRKramer** [comment]
Hi Dave -

The geometry you describe sounds like it might possibly be modeled as an ElongatedCylinder. If so, you might be able to use its Length element instead of two cylinders in a group with distance between.

Tom Kramer

**Comment by GitHubDaveSmith** [comment]
Hi Tom,

Thank you for your suggestion.

Actually the example I provided was just to illustrate one possible example. We would like to be able to describe both Distance Between and Angle Between characteristics between features that belong to a general (non-specific) GroupFeature element within the QIF. We are trying to create a software solution that will cater for any group, rather than group that contains a specific collection of features. The distance between might be between two planes, a plane and a circle, etc.

On another note: are you the same Tom Kramer who worked for NIST on the I++ spec?

Kind regards

Dave

**Comment by TomRKramer** [comment]
Hi Dave -

What you are trying to do is obviously much more general than the situation in my simple suggestion. I have no good ideas for the general problem today.

Yes, I am the same Tom Kramer who worked on I++. I just started my 38th year as a NIST Guest Researcher. My journal reminds me that I worked with you two decades ago on the CMM Driver spec and I++, including a CMM-spec demo with a DMIS program at NIST sending CMM Driver commands to a CMM in the UK. I've been working on QIF since 2011.

Best wishes.

Tom K

**Comment by GitHubDaveSmith** [comment]
Hi Tom,

It's good to hear from you and good to know that you are still around.

Two decades sounds like a very long time doesn't it! It's frightening how time flies.

I work for Renishaw now. Most of the team that worked on the Camio software moved to Renishaw in October 2008. We brought the software with us and turned it into a Renishaw product called Modus. It's hard to imagine that I've been here for over 12 years now.

I started a new project to create QIF from measurement data about a year ago so I am getting more used to QIF now. This particular problem might just need a custom attribute but I wanted to know if there was a better and more generic solution before doing that.

Thanks for your help anyway.

Kind regards

Dave

p.s. How's Bill Rippey?.. in good health, still working or playing the saxophone in retirement?
